FORMAT: 1A
HOST: http://innovated.qinmoxi.cn/service/public/index.php

# Quotation API

This is a API to query some information of quotation system.

# Group Manufacturer & Model
API-related resources of *Make & Model API*.

## Manufacturer [/makeModel/makes]
Query information of makes

The Manufacturer resource has the following attributes:

- success 
- data
- msg

### Query All Manufacturer [POST]
This API will get all of the *Manufacturers*.

- vcode_id (ID number of the manufacturer) 

- vcode_desc (Name of the manufacturer)

+ Response 200 (application/json)

        {
            "data": [{
                "vcode_id": "150",
                "vcode_desc": "Alfa Romeo",
                "vcode_parent": "0",
                "costpertyre": "0",
                "visible": "1"
            }, {
                "vcode_id": "36",
                "vcode_desc": "BMW",
                "vcode_parent": "0",
                "costpertyre": "250",
                "visible": "1"
            }, ],
            "success": true,
            "msg": "Query Makes Successfully."
        }
    
## Model [/makeModel/models]
Query information of models of one make

The Model resource has the following attributes:

- success 
- data
- msg


### Query Models of One Manufacturer [POST]

To query the models of the manufacturer provide a JSON hash of *ID number of the make*

- vcode_id (ID number of the model) 

- vcode_desc (Name of the model)

+ Request (application/json)

        {
            "make_id": "4"
        }

+ Response 200 (application/json)

        {
            "data": [{
                "vcode_id": "990",
                "vcode_desc": "300",
                "vcode_parent": "4",
                "costpertyre": null,
                "visible": "1"
            }, {
                "vcode_id": "1381",
                "vcode_desc": "300C",
                "vcode_parent": "4",
                "costpertyre": null,
                "visible": "1"
            }],
            "success": true,
            "msg": "Query Models Successfully."
        }
        
## Vehicle [/makeModel/list]
Query vehicle information

### Query Vehicle [POST]

To query vehicle information according to parameters like *make, model, body type*

*Single or mutiple parameters be allowed to request*

other parameter:

- limit (default: 0 | how many records response on one request)
- page (default: 1)
- sort (default: date_updated | sort field)
- sort_dir (default: DESC | sort order)
- model_id
- min_year
- max_year
- fuelType
- engineSize
- ...
            
+ Request (application/json)

        {
            "make_id": "4",
            "bodyType": "Wagon"
            
            
        }
        
+ Response 200 (application/json)

        {
            "success": true,
            "rows": [{
                "make_model_id": "1634",
                "make_id": "4",
                "model_id": "788",
                "model_nbr": "",
                "desc": "MY09",
                "abbr": "",
                "base_price": null,
                "turnover_time": "0",
                "turnover_kms": "0",
                "turnover_cost": "0",
                "serv_kms": "10000",
                "serv_mths": "6",
                "city_cycle": "0",
                "highway_cycle": "0",
                "combined_economy": "0",
                "tank_capacity": "0",
                "date_updated": "2014-10-04 11:43:31",
                "upd_by": "neilc",
                "sunny_time": "36",
                "sunny_kms": "75000",
                "engine_size": 3.8,
                "fuel_type": "2",
                "transmission": "Automatic",
                "body_type": "2",
                "display_str": "Chrysler Grand Voyager MY09 2009 3.8L Automatic Unleaded Wagon",
                "model_year": "2009",
                "tyre_size": "0",
                "driving_wheels": null,
                "driving_wheels_desc": null,
                "transmission_desc": null,
                "engine_configuration": null,
                "quote_id": null,
                "visible": "0",
                "belongs_to_v_type_make": {
                    "vcode_id": "4",
                    "vcode_desc": "Chrysler",
                    "vcode_parent": "0",
                    "costpertyre": "125",
                    "visible": "1"
                },
                "belongs_to_v_type_model": {
                    "vcode_id": "788",
                    "vcode_desc": "Grand Voyager",
                    "vcode_parent": "59",
                    "costpertyre": null,
                    "visible": "1"
                },
                "belongs_to_fuel_type": {
                    "id": "2",
                    "name": "Unleaded",
                    "category": "Petrol",
                    "created_at": "2016-04-20 06:05:08",
                    "updated_at": "2016-04-20 06:05:08"
                },
                "belongs_to_body_type": {
                    "id": "2",
                    "name": "Wagon",
                    "created_at": "2016-04-20 06:05:09",
                    "updated_at": "2016-04-20 06:05:09"
                },
                "pictures": []
            }, {
                "make_model_id": "1499",
                "make_id": "4",
                "model_id": "404",
                "model_nbr": "",
                "desc": "RT",
                "abbr": "",
                "base_price": null,
                "turnover_time": "0",
                "turnover_kms": "0",
                "turnover_cost": "0",
                "serv_kms": "10000",
                "serv_mths": "6",
                "city_cycle": "0",
                "highway_cycle": "0",
                "combined_economy": "0",
                "tank_capacity": "0",
                "date_updated": "2014-06-04 23:16:08",
                "upd_by": "neilc",
                "sunny_time": "36",
                "sunny_kms": "75000",
                "engine_size": 3.6,
                "fuel_type": "2",
                "transmission": "Automatic",
                "body_type": "2",
                "display_str": "Chrysler Journey RT 2014 3.6L Automatic Unleaded Wagon",
                "model_year": "2014",
                "tyre_size": null,
                "driving_wheels": null,
                "driving_wheels_desc": null,
                "transmission_desc": null,
                "engine_configuration": null,
                "quote_id": null,
                "visible": "0",
                "belongs_to_v_type_make": {
                    "vcode_id": "4",
                    "vcode_desc": "Chrysler",
                    "vcode_parent": "0",
                    "costpertyre": "125",
                    "visible": "1"
                },
                "belongs_to_v_type_model": {
                    "vcode_id": "404",
                    "vcode_desc": "Journey",
                    "vcode_parent": "237",
                    "costpertyre": null,
                    "visible": "1"
                },
                "belongs_to_fuel_type": {
                    "id": "2",
                    "name": "Unleaded",
                    "category": "Petrol",
                    "created_at": "2016-04-20 06:05:08",
                    "updated_at": "2016-04-20 06:05:08"
                },
                "belongs_to_body_type": {
                    "id": "2",
                    "name": "Wagon",
                    "created_at": "2016-04-20 06:05:09",
                    "updated_at": "2016-04-20 06:05:09"
                },
                "pictures": []
            }],
            "total": 0,
            "page": "1",
            "records": 2,
            "pageSize": "0"
        }